defmodule SafeNIFTest.TestNIF do
  @moduledoc """
  A deliberately crashy NIF for testing SafeNIF's isolation capabilities.

  **WARNING**: The crash functions in this module WILL crash the BEAM node.
  Only use them via SafeNIF.wrap/2 or on expendable peer nodes.

  Generated by Claude and reviewed by @probably-not.
  """

  @on_load :load_nif

  @doc false
  def load_nif do
    path = :filename.join(:code.priv_dir(:safe_nif), ~c"test_nif")

    case :erlang.load_nif(path, 0) do
      :ok -> :ok
      {:error, {:reload, _}} -> :ok
      {:error, reason} -> {:error, reason}
    end
  end

  @doc """
  Crashes via null pointer dereference (SIGSEGV).
  """
  @spec crash_segfault() :: no_return()
  def crash_segfault do
    :erlang.nif_error(:nif_not_loaded)
  end

  @doc """
  Crashes via abort() (SIGABRT).
  """
  @spec crash_abort() :: no_return()
  def crash_abort do
    :erlang.nif_error(:nif_not_loaded)
  end

  @doc """
  Crashes via stack overflow.
  """
  @spec crash_stack_overflow() :: no_return()
  def crash_stack_overflow do
    :erlang.nif_error(:nif_not_loaded)
  end

  @doc """
  Crashes via division by zero (platform-dependent behavior).
  """
  @spec crash_div_zero() :: no_return()
  def crash_div_zero do
    :erlang.nif_error(:nif_not_loaded)
  end

  @doc """
  A safe function that returns :ok.
  """
  @spec safe_noop() :: :ok
  def safe_noop do
    :erlang.nif_error(:nif_not_loaded)
  end

  @doc """
  A safe function that adds two integers.
  """
  @spec safe_add(integer(), integer()) :: integer()
  def safe_add(_a, _b) do
    :erlang.nif_error(:nif_not_loaded)
  end
end
